# Generated by Django 6.0.5 on 2026-05-23 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Objective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("success_metric", models.CharField(blank=True, max_length=255)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=32,
                    ),
                ),
                ("status", models.CharField(default="draft", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaskLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("task_type", models.CharField(max_length=100)),
                (
                    "owner_agent_label",
                    models.CharField(default="assistant", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("blocked", "Blocked"),
                            ("archived", "Archived"),
                        ],
                        default="proposed",
                        max_length=32,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=32,
                    ),
                ),
                ("approval_required", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("execution_lineage", models.JSONField(blank=True, default=dict)),
                ("governance", models.JSONField(blank=True, default=dict)),
                ("inputs", models.JSONField(blank=True, default=dict)),
                ("telemetry", models.JSONField(blank=True, default=dict)),
                ("outputs", models.JSONField(blank=True, default=dict)),
                ("evaluation", models.JSONField(blank=True, default=dict)),
                ("next_actions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "objective",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="strategy.objective",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationScorecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relevance", models.FloatField(blank=True, null=True)),
                ("quality", models.FloatField(blank=True, null=True)),
                ("evidence_strength", models.FloatField(blank=True, null=True)),
                ("actionability", models.FloatField(blank=True, null=True)),
                ("executive_readiness", models.FloatField(blank=True, null=True)),
                ("style_alignment", models.FloatField(blank=True, null=True)),
                ("local_context", models.FloatField(blank=True, null=True)),
                ("novelty", models.FloatField(blank=True, null=True)),
                ("overall_score", models.FloatField(blank=True, null=True)),
                ("reviewer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecards",
                        to="strategy.taskledgerentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("strategic_context", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("deleted", "Deleted"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="taskledgerentry",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="strategy.topic",
            ),
        ),
        migrations.AddField(
            model_name="objective",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objectives",
                to="strategy.topic",
            ),
        ),
        migrations.CreateModel(
            name="MemoryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "memory_type",
                    models.CharField(
                        choices=[
                            ("user_preference", "User Preference"),
                            ("project_context", "Project Context"),
                            ("feedback", "Feedback"),
                            ("style_rule", "Style Rule"),
                            ("source_insight", "Source Insight"),
                        ],
                        max_length=64,
                    ),
                ),
                ("content", models.TextField()),
                ("source", models.CharField(blank=True, max_length=255)),
                ("confidence", models.FloatField(default=1.0)),
                ("approved_for_reuse", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_feedback", models.TextField()),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("quality", "Quality"),
                            ("relevance", "Relevance"),
                            ("style", "Style"),
                            ("accuracy", "Accuracy"),
                            ("usefulness", "Usefulness"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=32,
                    ),
                ),
                ("improvement_suggestion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.taskledgerentry",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workstream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("competitive_analysis", "Competitive Analysis"),
                            ("market_metrics", "Market Metrics"),
                            ("implementation_plan", "Implementation Plan"),
                            ("risk_analysis", "Risk Analysis"),
                            ("product_strategy", "Product Strategy"),
                            ("roadmap", "Roadmap"),
                            ("execution_tracking", "Execution Tracking"),
                        ],
                        max_length=64,
                    ),
                ),
                ("status", models.CharField(default="active", max_length=32)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workstreams",
                        to="strategy.topic",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="taskledgerentry",
            name="workstream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="strategy.workstream",
            ),
        ),
    ]
