# Generated by Django 5.1.3 on 2026-05-24 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "strategy",
            "0002_alter_evaluationscorecard_id_alter_feedbackrecord_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("email_draft", "Email Draft"),
                            ("email_send", "Email Send"),
                            ("document_create", "Document Create"),
                            ("stakeholder_update", "Stakeholder Update"),
                            ("research_request", "Research Request"),
                            ("follow_up_task", "Follow-up Task"),
                        ],
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("instruction", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("drafted", "Drafted"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("approved", "Approved"),
                            ("executed", "Executed"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="proposed",
                        max_length=64,
                    ),
                ),
                ("risk_level", models.CharField(default="medium", max_length=32)),
                ("approval_required", models.BooleanField(default=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("generated_output", models.JSONField(blank=True, default=dict)),
                ("execution_result", models.JSONField(blank=True, default=dict)),
                ("telemetry", models.JSONField(blank=True, default=dict)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="strategy.taskledgerentry",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="strategy.topic",
                    ),
                ),
            ],
        ),
    ]
