# Generated by Django 6.0.5 on 2026-06-08 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "strategy",
            "0005_alter_actionrequest_id_alter_conversationmessage_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("interpretation", models.TextField()),
                ("relevance", models.TextField()),
                ("confidence", models.FloatField(default=0.7)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.taskledgerentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objective", models.TextField()),
                ("research_questions", models.JSONField(default=list)),
                ("status", models.CharField(default="draft", max_length=50)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.taskledgerentry",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="strategy.topic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("markdown", models.TextField()),
                ("html", models.TextField(blank=True)),
                (
                    "doc_type",
                    models.CharField(default="research_report", max_length=100),
                ),
                ("status", models.CharField(default="draft", max_length=50)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.taskledgerentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finding", models.TextField()),
                ("implication", models.TextField()),
                ("confidence", models.FloatField(default=0.7)),
                ("evidence", models.ManyToManyField(to="strategy.evidencequote")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.taskledgerentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(blank=True)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("source_type", models.CharField(max_length=100)),
                ("retrieved_at", models.DateTimeField(auto_now_add=True)),
                ("credibility_score", models.FloatField(default=0)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.taskledgerentry",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="strategy.topic"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evidencequote",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="strategy.sourcerecord"
            ),
        ),
    ]
