# Generated by Django 5.1.3 on 2026-06-13 21:14

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        (
            "strategy",
            "0007_alter_actionrequest_id_alter_conversationmessage_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="topic",
            name="workspace_type",
            field=models.CharField(
                choices=[
                    ("strategy", "Strategy Workspace"),
                    ("custom_agent_chain", "Custom Agent Chain Workspace"),
                ],
                default="strategy",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="voicetranscriptrecord",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="voicetranscriptrecord",
            name="telemetry",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="AgentDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("system_prompt", models.TextField()),
                ("instructions", models.TextField(blank=True)),
                ("input_schema", models.JSONField(blank=True, default=dict)),
                ("output_schema", models.JSONField(default=dict)),
                (
                    "memory_scope",
                    models.CharField(
                        choices=[
                            ("agent_only", "Agent Only"),
                            ("workspace_shared", "Workspace Shared"),
                            ("none", "No Memory"),
                        ],
                        default="agent_only",
                        max_length=50,
                    ),
                ),
                ("rag_collection_id", models.CharField(blank=True, max_length=255)),
                ("model_name", models.CharField(default="default", max_length=100)),
                ("temperature", models.FloatField(default=0.2)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("is_entrypoint", models.BooleanField(default=False)),
                ("is_terminal", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_definitions",
                        to="strategy.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentEdge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                ("data_mapping", models.JSONField(blank=True, default=dict)),
                ("condition", models.JSONField(blank=True, default=dict)),
                ("requires_approval", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="strategy.agentdefinition",
                    ),
                ),
                (
                    "target_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="strategy.agentdefinition",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_edges",
                        to="strategy.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentMemoryCollection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("collection_key", models.CharField(max_length=255, unique=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private_to_agent", "Private to Agent"),
                            ("workspace_shared", "Workspace Shared"),
                        ],
                        default="private_to_agent",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.agentdefinition",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="strategy.topic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentMemoryChunk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_title", models.CharField(max_length=500)),
                ("source_uri", models.TextField(blank=True)),
                ("chunk_text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="strategy.agentmemorycollection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChainExecutionVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("trigger_input", models.JSONField(default=dict)),
                ("graph_snapshot", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_versions",
                        to="strategy.topic",
                    ),
                ),
            ],
            options={
                "unique_together": {("topic", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="AgentRunTrace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_order", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("awaiting_approval", "Awaiting Approval"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("input_payload", models.JSONField(default=dict)),
                ("mapped_input_payload", models.JSONField(default=dict)),
                ("memory_context_used", models.JSONField(default=list)),
                ("prompt_snapshot", models.TextField(blank=True)),
                ("output_payload", models.JSONField(default=dict)),
                ("validation_result", models.JSONField(default=dict)),
                ("telemetry", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="strategy.agentdefinition",
                    ),
                ),
                (
                    "execution_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_traces",
                        to="strategy.chainexecutionversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentArtifact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("markdown", "Markdown"),
                            ("html", "HTML"),
                            ("json", "JSON"),
                            ("document", "Document"),
                            ("table", "Table"),
                            ("image_reference", "Image Reference"),
                        ],
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.agentruntrace",
                    ),
                ),
                (
                    "execution_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.chainexecutionversion",
                    ),
                ),
            ],
        ),
    ]
