# Generated by Django 5.1.3 on 2026-06-13 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0008_topic_workspace_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("safety", "Safety"),
                            ("research", "Research"),
                            ("reasoning", "Reasoning"),
                            ("writing", "Writing"),
                            ("evaluation", "Evaluation"),
                            ("memory", "Memory"),
                            ("custom", "Custom"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("prompt_body", models.TextField()),
                ("version", models.IntegerField(default=1)),
                ("is_system_prompt", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptExecutionTrace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("prompt_snapshot", models.TextField()),
                ("execution_order", models.IntegerField()),
                (
                    "agent_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.agentruntrace",
                    ),
                ),
                (
                    "prompt_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="strategy.prompttemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentPromptAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("required", models.BooleanField(default=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_assignments",
                        to="strategy.agentdefinition",
                    ),
                ),
                (
                    "prompt_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.prompttemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptTemplateVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("prompt_body", models.TextField()),
                ("changelog", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.prompttemplate",
                    ),
                ),
            ],
        ),
    ]
