# Generated by Django 5.1.3 on 2026-06-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0009_prompttemplate_promptexecutiontrace_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationscorecard",
            name="hallucination_detected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evaluationscorecard",
            name="user_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
