# Generated by Django 5.1.3 on 2026-06-13 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0010_evaluationscorecard_hallucination_detected_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptVersionMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tasks_used_count", models.PositiveIntegerField(default=0)),
                ("acceptance_rate", models.FloatField(default=0.0)),
                ("average_executive_score", models.FloatField(default=0.0)),
                ("average_user_score", models.FloatField(default=0.0)),
                ("failure_rate", models.FloatField(default=0.0)),
                ("hallucination_rate", models.FloatField(default=0.0)),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="strategy.prompttemplateversion",
                    ),
                ),
            ],
        ),
    ]
