# Generated by Django 5.1.3 on 2026-06-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0011_promptversionmetrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptPack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "templates",
                    models.ManyToManyField(
                        related_name="packs", to="strategy.prompttemplate"
                    ),
                ),
            ],
        ),
    ]
