# Generated by Django 5.1.3 on 2026-06-13 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0012_promptpack"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("quality", "Quality"),
                            ("evidence", "Evidence"),
                            ("strategy", "Strategy"),
                            ("product", "Product"),
                            ("executive", "Executive"),
                            ("safety", "Safety"),
                            ("writing", "Writing"),
                            ("custom", "Custom"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("evaluation_prompt", models.TextField()),
                ("version", models.IntegerField(default=1)),
                ("scoring_schema", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentEvaluationHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.FloatField()),
                ("quality_score", models.FloatField(default=0.0)),
                ("evidence_score", models.FloatField(default=0.0)),
                ("executive_score", models.FloatField(default=0.0)),
                ("hallucination_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.agentdefinition",
                    ),
                ),
                (
                    "execution_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.chainexecutionversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.JSONField()),
                ("overall_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.agentruntrace",
                    ),
                ),
                (
                    "evaluation_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="strategy.evaluationtemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationPack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "templates",
                    models.ManyToManyField(
                        related_name="packs", to="strategy.evaluationtemplate"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.agentdefinition",
                    ),
                ),
                (
                    "evaluation_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.evaluationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
