# Generated by Django 5.1.3 on 2026-06-14 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0013_evaluationtemplate_agentevaluationhistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcerecord",
            name="agent_trace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="strategy.agentruntrace",
            ),
        ),
        migrations.AlterField(
            model_name="sourcerecord",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="strategy.taskledgerentry",
            ),
        ),
    ]
