# Generated by Django 5.1.3 on 2026-06-14 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0014_sourcerecord_agent_trace_alter_sourcerecord_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourcerecord",
            name="credibility_score",
        ),
        migrations.RemoveField(
            model_name="sourcerecord",
            name="task",
        ),
        migrations.AddField(
            model_name="sourcerecord",
            name="content_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sourcerecord",
            name="relevance_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sourcerecord",
            name="agent_trace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                to="strategy.agentruntrace",
            ),
        ),
        migrations.AlterField(
            model_name="sourcerecord",
            name="source_type",
            field=models.CharField(default="web", max_length=100),
        ),
        migrations.AlterField(
            model_name="sourcerecord",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_records",
                to="strategy.topic",
            ),
        ),
        migrations.AlterField(
            model_name="sourcerecord",
            name="url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.CreateModel(
            name="ManualSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(blank=True, max_length=2000)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_sources",
                        to="strategy.agentdefinition",
                    ),
                ),
            ],
        ),
    ]
