# Generated by Django 5.1.3 on 2026-06-15 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0015_remove_sourcerecord_credibility_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentImprovementRecommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_type", models.CharField(max_length=100)),
                ("source_evaluation", models.CharField(max_length=255)),
                ("problem", models.TextField()),
                ("recommended_change", models.TextField()),
                (
                    "target_area",
                    models.CharField(
                        choices=[
                            ("prompt", "Prompt"),
                            ("memory", "Memory"),
                            ("rag_sources", "RAG Sources"),
                            ("output_schema", "Output Schema"),
                            ("tooling", "Tooling"),
                            ("workflow", "Workflow"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("applied", "Applied"),
                        ],
                        default="proposed",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.agentdefinition",
                    ),
                ),
                (
                    "agent_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.agentruntrace",
                    ),
                ),
                (
                    "execution_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.chainexecutionversion",
                    ),
                ),
            ],
        ),
    ]
