# Generated by Django 5.1.3 on 2026-06-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0016_agentimprovementrecommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationtemplate",
            name="score_field",
            field=models.CharField(
                default="score",
                help_text="The JSON key in the output schema containing the numeric score",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="prompttemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("safety", "Safety"),
                    ("research", "Research"),
                    ("reasoning", "Reasoning"),
                    ("writing", "Writing"),
                    ("evaluation", "Evaluation"),
                    ("memory", "Memory"),
                    ("improvement_rule", "Improvement Rule"),
                    ("custom", "Custom"),
                ],
                max_length=100,
            ),
        ),
    ]
