# Generated by Django 5.1.3 on 2026-06-15 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0018_evaluationpack_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agentimprovementrecommendation",
            name="confidence_score",
            field=models.FloatField(
                default=0.0, help_text="Computed confidence in this recommendation"
            ),
        ),
        migrations.AddField(
            model_name="agentimprovementrecommendation",
            name="recurring_count",
            field=models.IntegerField(
                default=1, help_text="Number of times this issue was observed"
            ),
        ),
        migrations.AddField(
            model_name="agentimprovementrecommendation",
            name="root_cause_diagnosis",
            field=models.TextField(
                blank=True, help_text="The detected root cause underlying the low score"
            ),
        ),
        migrations.AlterField(
            model_name="agentimprovementrecommendation",
            name="problem",
            field=models.TextField(help_text="Detailed problem description"),
        ),
        migrations.AlterField(
            model_name="agentimprovementrecommendation",
            name="recommended_change",
            field=models.TextField(help_text="Actionable fix recommendation"),
        ),
        migrations.AlterField(
            model_name="agentimprovementrecommendation",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "Proposed"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("applied", "Applied"),
                    ("monitoring", "Monitoring"),
                    ("successful", "Successful"),
                    ("failed", "Failed"),
                    ("rolled_back", "Rolled Back"),
                ],
                default="proposed",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="agentimprovementrecommendation",
            name="target_area",
            field=models.CharField(
                choices=[
                    ("prompt", "Prompt"),
                    ("memory", "Memory"),
                    ("rag_sources", "RAG Sources"),
                    ("output_schema", "Output Schema"),
                    ("tooling", "Tooling"),
                    ("workflow", "Workflow"),
                    ("human_instruction", "Human Instruction Needed"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AgentImprovementExperiment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baseline_score", models.FloatField()),
                ("post_change_score", models.FloatField(blank=True, null=True)),
                ("delta", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("monitoring", "Monitoring"),
                            ("successful", "Successful"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="monitoring",
                        max_length=50,
                    ),
                ),
                ("runs_observed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.agentdefinition",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.agentimprovementrecommendation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HumanOutputReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted_unchanged", "Accepted Unchanged"),
                            ("accepted_with_edits", "Accepted With Edits"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("edited_sections", models.JSONField(blank=True, default=dict)),
                ("feedback_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.agentruntrace",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
