# Generated by Django 5.1.3 on 2026-06-16 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0019_agentimprovementrecommendation_confidence_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentimprovementexperiment",
            name="failure_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentimprovementrecommendation",
            name="applied_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="strategy.agentpromptassignment",
            ),
        ),
        migrations.AddField(
            model_name="humanoutputreview",
            name="score",
            field=models.IntegerField(
                blank=True, help_text="Human score out of 10", null=True
            ),
        ),
    ]
