# Generated by Django 5.1.3 on 2026-06-16 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0021_agentruntrace_active_experiments"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemExecutionEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("evaluation_failed", "Evaluation Failed"),
                            ("rate_limit", "Rate Limit"),
                            ("schema_error", "Schema Error"),
                            ("provider_error", "Provider Error"),
                            ("trace_error", "Trace Error"),
                            ("artifact_error", "Artifact Error"),
                            ("configuration_error", "Configuration Error"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("technical_details", models.JSONField(blank=True, default=dict)),
                ("suggested_fix", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="strategy.agentdefinition",
                    ),
                ),
                (
                    "agent_trace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="strategy.agentruntrace",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="strategy.topic",
                    ),
                ),
            ],
        ),
    ]
