# Generated by Django 5.1.3 on 2026-06-17 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0022_systemexecutionevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchSearchQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("intent", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.agentdefinition",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="strategy.topic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrendEvidenceRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snippet", models.TextField()),
                ("trend_signal", models.TextField()),
                ("future_relevance", models.TextField()),
                ("impact_area", models.CharField(max_length=100)),
                ("confidence_score", models.FloatField(default=0.7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.agentruntrace",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.sourcerecord",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="strategy.topic"
                    ),
                ),
            ],
        ),
    ]
