# Generated by Django 5.1.3 on 2026-06-20 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0026_add_agent_type_to_agentdefinition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webpageartifact",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="agentruntrace",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="strategy.agentdefinition",
            ),
        ),
    ]
