# Generated by Django 5.1.3 on 2026-06-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0027_alter_webpageartifact_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
