# Generated by Django 5.1.3 on 2026-06-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0028_add_name_and_nullable_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentdefinition",
            name="allowed_inputs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="agentdefinition",
            name="output_artifact_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="agentdefinition",
            name="purpose",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agentdefinition",
            name="requires_code_generation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agentdefinition",
            name="requires_human_review",
            field=models.BooleanField(default=False),
        ),
    ]
