from strategy.models import (
    PromptTemplateVersion,
    PromptVersionMetrics,
    PromptExecutionTrace,
    EvaluationScorecard,
    ActionRequest
)
from django.db.models import Avg

def calculate_prompt_metrics(version_id: int):
    """
    Recalculates and updates the PromptVersionMetrics for a given PromptTemplateVersion.
    """
    version = PromptTemplateVersion.objects.get(id=version_id)
    
    # Get or create the metrics object
    metrics, created = PromptVersionMetrics.objects.get_or_create(prompt_version=version)
    
    # 1. Calculate Tasks Used Count
    traces = PromptExecutionTrace.objects.filter(
        prompt_template=version.prompt_template,
        version_number=version.version_number
    )
    tasks_used = traces.count()
    metrics.tasks_used_count = tasks_used
    
    if tasks_used == 0:
        metrics.save()
        return metrics

    # 2. Calculate Failure Rate
    # A failure is an AgentRunTrace that failed.
    failed_traces = traces.filter(agent_trace__status="failed").count()
    metrics.failure_rate = (failed_traces / tasks_used) * 100.0

    # 3. Calculate Acceptance Rate
    # Since we don't have a hard DB link from AgentRunTrace -> ActionRequest yet,
    # we simulate this based on the number of completed traces vs. a global ratio for now.
    completed_traces = traces.filter(agent_trace__status="completed").count()
    metrics.acceptance_rate = (completed_traces / tasks_used) * 100.0 if tasks_used > 0 else 0.0

    # 4. Calculate Scores and Hallucination Rate from EvaluationScorecard
    # Ideally we trace AgentRunTrace -> Task -> Scorecard.
    # For now, we will aggregate all scorecards to give a baseline, 
    # but in a real system this would join on the exact Tasks generated by this prompt.
    scorecards = EvaluationScorecard.objects.all()
    if scorecards.exists():
        exec_avg = scorecards.aggregate(Avg('executive_readiness'))['executive_readiness__avg'] or 0.0
        user_avg = scorecards.aggregate(Avg('user_score'))['user_score__avg'] or 0.0
        hallucination_count = scorecards.filter(hallucination_detected=True).count()
        total_scorecards = scorecards.count()
        
        metrics.average_executive_score = exec_avg
        metrics.average_user_score = user_avg
        metrics.hallucination_rate = (hallucination_count / total_scorecards) * 100.0 if total_scorecards > 0 else 0.0

    metrics.save()
    return metrics
