import React, { useState, useEffect, useCallback } from 'react';
import { api } from '../../api';
import { FileText, Loader, Search, RefreshCw, X } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const ArtifactsDashboard = ({ topicId }) => {
  const [artifacts, setArtifacts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedArtifact, setSelectedArtifact] = useState(null);

  const fetchArtifacts = useCallback(async () => {
    try {
      setLoading(true);
      const res = await api.get(`/api/topics/${topicId}/agent-artifacts/`);
      setArtifacts(res.data);
    } catch (err) {
      console.error("Failed to load artifacts", err);
    } finally {
      setLoading(false);
    }
  }, [topicId]);

  useEffect(() => {
    fetchArtifacts();
  }, [fetchArtifacts]);

  if (loading && artifacts.length === 0) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center text-gray-500">
        <Loader className="animate-spin mb-4" size={32} />
        <p>Loading generated artifacts...</p>
      </div>
    );
  }

  return (
    <div className="flex-1 flex bg-white overflow-hidden" data-testid="artifacts-dashboard">
      {/* List Panel */}
      <div className={`flex flex-col border-r border-gray-200 ${selectedArtifact ? 'w-80' : 'w-full max-w-4xl mx-auto'}`}>
        <div className="p-4 border-b border-gray-200 flex items-center justify-between bg-gray-50">
          <h2 className="text-lg font-semibold text-gray-800 flex items-center gap-2">
            <FileText className="text-indigo-600" size={20} />
            Generated Documents & Artifacts
          </h2>
          <button 
            onClick={fetchArtifacts}
            className="p-1.5 text-gray-500 hover:text-indigo-600 rounded-md hover:bg-gray-200 transition-colors"
            title="Refresh Artifacts"
          >
            <RefreshCw size={16} />
          </button>
        </div>
        
        <div className="flex-1 overflow-y-auto p-4 space-y-3 bg-gray-50">
          {artifacts.length === 0 ? (
            <div className="text-center p-8 text-gray-500 border border-dashed border-gray-300 rounded-lg bg-white">
              <FileText size={48} className="mx-auto mb-4 text-gray-300" />
              <p>No artifacts generated yet.</p>
              <p className="text-xs mt-2">Run chains with agents configured to produce markdown outputs to see them here.</p>
            </div>
          ) : (
            artifacts.map(art => (
              <div 
                key={art.id}
                onClick={() => setSelectedArtifact(art)}
                className={`p-4 rounded-xl border cursor-pointer transition-all ${
                  selectedArtifact?.id === art.id 
                    ? 'border-indigo-500 bg-indigo-50 shadow-sm' 
                    : 'border-gray-200 bg-white hover:border-indigo-300 hover:shadow-sm'
                }`}
              >
                <div className="flex items-start justify-between mb-2">
                  <h3 className="font-semibold text-gray-800 truncate" title={art.title}>{art.title}</h3>
                  <span className="text-[10px] font-mono bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full border border-gray-200 whitespace-nowrap ml-2">
                    v{art.execution_version_number}
                  </span>
                </div>
                <div className="flex items-center gap-2 text-xs text-gray-500 mb-2">
                  <span className="bg-indigo-100 text-indigo-700 px-1.5 py-0.5 rounded capitalize">{art.artifact_type}</span>
                  <span>from {art.agent_name}</span>
                </div>
                <p className="text-xs text-gray-400 line-clamp-2">
                  {art.content}
                </p>
              </div>
            ))
          )}
        </div>
      </div>

      {/* Detail Viewer */}
      {selectedArtifact && (
        <div className="flex-1 flex flex-col bg-white overflow-hidden shadow-xl z-10 relative">
          <div className="p-4 border-b border-gray-200 flex items-center justify-between bg-white shrink-0">
            <div>
              <h2 className="text-lg font-bold text-gray-900">{selectedArtifact.title}</h2>
              <div className="flex items-center gap-3 mt-1 text-xs text-gray-500">
                <span>Generated by <span className="font-medium text-gray-700">{selectedArtifact.agent_name}</span></span>
                <span>•</span>
                <span>Chain Version v{selectedArtifact.execution_version_number}</span>
              </div>
            </div>
            <button 
              onClick={() => setSelectedArtifact(null)}
              className="p-2 text-gray-400 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
            >
              <X size={20} />
            </button>
          </div>
          <div className="flex-1 overflow-y-auto p-8 bg-gray-50">
            <div className="max-w-4xl mx-auto bg-white border border-gray-200 rounded-xl shadow-sm p-8 prose prose-indigo max-w-none">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {selectedArtifact.content}
              </ReactMarkdown>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ArtifactsDashboard;
